### ISSUE TITLE
ImportError: cannot import name 'ball_query_ext' from 'third_party.mmdet3d.ops.ball_query' (/home/mars/dpc/SpOT/third_party/mmdet3d/ops/ball_query/__init__.py)

### ISSUE THREAD

**Issue by RaymonHE** [coltonstearns/SpOT#4]
Hi, Colton. When implementing the pre-trained code, I encountered the problem below.  Can you help me to fix this problem? Thanks.

**_What did I input in the terminal?_**
python test.py --config=configs/reported_eval/waymo_reported_vehicle.yaml --general.out=../out/waymo_vehicle

**_What is the output?_**
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    from spot.utils.test_utils import TrackAndEvaluateNuscenes, TrackAndEvaluateWaymo
  File "/home/mars/dpc/SpOT/spot/utils/test_utils.py", line 8, in <module>
    from spot.tracking_utils.track_scene import SceneTracking
  File "/home/mars/dpc/SpOT/spot/tracking_utils/track_scene.py", line 2, in <module>
    from spot.tracking_utils.association import TrackManager
  File "/home/mars/dpc/SpOT/spot/tracking_utils/association.py", line 7, in <module>
    from spot.io.wandb_utils import get_wandb_boxes, get_boxdir_points
  File "/home/mars/dpc/SpOT/spot/io/wandb_utils.py", line 13, in <module>
    from spot.tracking_utils.object_representation import MergedEnhancedAndBaseObjectRepresentations, EmptySTObjectRepresentations
  File "/home/mars/dpc/SpOT/spot/tracking_utils/object_representation.py", line 7, in <module>
    from third_party.mmdet3d.ops.iou3d.iou3d_utils import nms_gpu, boxes_iou_bev
  File "/home/mars/dpc/SpOT/third_party/mmdet3d/ops/__init__.py", line 5, in <module>
    from .ball_query import ball_query
  File "/home/mars/dpc/SpOT/third_party/mmdet3d/ops/ball_query/ball_query.py", line 4, in <module>
    from . import ball_query_ext
ImportError: cannot import name 'ball_query_ext' from 'third_party.mmdet3d.ops.ball_query' (/home/mars/dpc/SpOT/third_party/mmdet3d/ops/ball_query/__init__.py)

**Comment by coltonstearns** [comment]
This is because you never compiled the code during installation - running `CUDA_VISIBLE_DEVICES=0 python setup.py develop` should resolve this.

**Comment by RaymonHE** [comment]
Hi Coltonm I recreated the environment yesterday by running this 
**_bash setup.sh /home/colton/anaconda3 spot_env
Then i should input this line, right?
CUDA_VISIBLE_DEVICES=0 python setup.py develop
It seems like it didn't work.

![2024-02-01 09-42-04屏幕截图](https://github.com/coltonstearns/SpOT/assets/49650511/77539a18-712e-4328-bf8f-2908fa763643)

**Comment by RaymonHE** [comment]
Hi, Colton. I solved these problems by docker. I can share this image as you can let me know if you like.
